services:
  knode:
    image: knode
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - './kdata:/kdata'
  chain:
    image: knode
    command: chain
    restart: always
    volumes:
      - './kdata:/kdata'
  bakWorker:
    image: knode
    command: bakWorker
    restart: always
    volumes:
      - './kdata:/kdata'
  kworker:
    image: knode
    command: worker
    restart: always
    volumes:
      - './kdata:/kdata'
version: '2'