services:
  knode:
    image: knode
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - './kdata:/kdata'
    links:
      - kchain
    depends_on:
      - kchain

  kchain:
    restart: always
    ports:
      - '46656:46656'
      - '46657:46657'
    volumes:
      - './kdata:/kdata'
    image: kchain

#  db:
#    image: mysql
#    restart: always
#    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
#    ports:
#      - '3306:3306'
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456
#      - MYSQL_DATABASE=yuanbenlian
#      - MYSQL_PORT_3306_TCP_ADDR=0.0.0.0
#    volumes:
#      - './kdata/datadir:/var/lib/mysql'

version: '2'
