abci: http://kchain:46657
config: /kdata/config
home_path: /kdata
priv_validator: /kdata/config/priv_validator.json

debug: true
log_level: info

store_type: sqlite
sqliteDb: knode.sqlite
mysqlDb: root:123456@tcp(db:3306)/yuanbenlian?charset=utf8mb4&parseTime=True


redis: redis://:yb12345@47.75.89.22:9221/0

bind_addr: 0.0.0.0
bind_port: 8081
advertise_addr: localhost
advertise_port: 8081