abci: http://kchain:46657
config: /kdata/config
home_path: /kdata
priv_validator: /kdata/config/priv_validator.json
external_ip: ""

addr: :8080
debug: true
log_level: info

store_type: sqlite
sqliteDb: knode.sqlite
mysqlDb: root:123456@tcp(db:3306)/yuanbenlian?charset=utf8mb4&parseTime=True

is_auth_filter: false
redis: redis://:123456@localhost:9221/0
bind_addr: 0.0.0.0
bind_port: 8081
advertise_addr: localhost
advertise_port: 8081